---
title: "test"
author: "yiru wang"
date: '2022-09-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(furrr)
library(lubridate)
library(rnaturalearth)
library(dplyr)
library(geojsonsf)
library(stringr)
library(highcharter)
library(leaflet)
library(leaflet.extras)
```
# read json from web and converted to sf format
```{r}
recent_hotspot_data <- geojsonsf::geojson_sf("https://hotspots.dea.ga.gov.au/data/recent-hotspots.json")
```

```{r}
recent_hotspot_data = recent_hotspot_data %>%
  filter(between(longitude, 112, 155)) %>% 
  filter(between(latitude, -44, -10))
```


```{r}
vic_hotspot1 <- recent_hotspot_data %>%
  st_set_crs("WGS 84")
```

```{r}
au_map <-ne_states(country = c("australia"), returnclass ="sf")%>%
  select(state = name, geometry)
vic_map <- au_map%>%
  filter(state == "Victoria")
```


```{r}
vic_map <- vic_map %>%st_set_crs("WGS 84")
recent_hotspot_data <- recent_hotspot_data %>%st_set_crs("WGS 84")
vic_hotspot2 = st_intersects(vic_map$geometry, recent_hotspot_data$geometry)
vic_hotspot2 = vic_hotspot1[vic_hotspot2[[1]],]
```

```{r}
hotspot_show <- vic_hotspot2%>%
  filter(confidence > 50)
```


```{r}
basemap <- leaflet() %>%
  # add different provider tiles
  addProviderTiles(
    "OpenStreetMap",
    # give the layer a name
    group = "OpenStreetMap"
  ) %>%
  addProviderTiles(
    "Stamen.Toner",
    group = "Stamen.Toner"
  ) %>%
  addProviderTiles(
    "Stamen.Terrain",
    group = "Stamen.Terrain"
  ) %>%
  addProviderTiles(
    "Esri.WorldStreetMap",
    group = "Esri.WorldStreetMap"
  ) %>%
  addProviderTiles(
    "Wikimedia",
    group = "Wikimedia"
  ) %>%
  addProviderTiles(
    "CartoDB.Positron",
    group = "CartoDB.Positron"
  ) %>%
  addProviderTiles(
    "Esri.WorldImagery",
    group = "Esri.WorldImagery"
  ) %>%
# add a layers control
  addLayersControl(
    baseGroups = c(
      "OpenStreetMap", "Stamen.Toner",
      "Stamen.Terrain", "Esri.WorldStreetMap",
      "Wikimedia", "CartoDB.Positron", "Esri.WorldImagery"
    ),
    # position it on the topleft
    position = "topleft"
  )
```

```{r}
basemap
```

```{r}
icon.fa <- makeAwesomeIcon(
  icon = "flag", markerColor = "red",
  library = "fa",
  iconColor = "black"
)

map_1 <- basemap %>%
  addAwesomeMarkers(
    lat = 48.1,
    lng = 11.5,
    label = "Starting point",
    icon = icon.fa
  )

map_1
```

```{r}
hotspot_show$hours_since_hotspot_class <- cut(hotspot_show$hours_since_hotspot,
                                        breaks = c(0,2,6,24,48,72),
                                        labels =c("0-2","2-6","6-24","24-48","48-72"))
pals = colorFactor(palette =c("#800000","#FF0000","#FF4500","#FF8C00","#F5DEB3"),
                   levels = c("0-2","2-6","6-24","24-48","48-72"))
```


```{r}
map_2 <- basemap %>%
  addCircles(
    data = hotspot_show,
    color = ~pals(hours_since_hotspot_class),
    # create custom labels
    label = paste(
      "Time: ", hotspot_show$load_dt, "<br>",
      "Hours: ",hotspot_show$hours_since_hotspot,  "<br>",
      "Satellite: ", hotspot_show$satellite_operating_agency
    ) %>%
      lapply(htmltools::HTML)
  ) %>%
  # add a legend
  addLegend(
    colors = c("#800000","#FF0000","#FF4500","#FF8C00","#F5DEB3"),
    labels = c("0 - 2 hours","2 - 6 hours","6 - 24 hours","24 - 48 hours","48 - 72 hours"),
    title = "Hours",
    opacity = 1, 
    position = "bottomleft"
  )

map_2
```

```{r}
vic_hotspot_test <- vic_hotspot
```

```{r}
vic_hotspot_test$load_dt <- str_replace(vic_hotspot$load_dt,"T"," ")
vic_hotspot_test$load_dt <- str_replace(vic_hotspot_test$load_dt,"Z"," ")
```

```{r}
vic_hotspot_test <- vic_hotspot_test%>%
  mutate(load_dt = as.POSIXct(load_dt))
```

```{r}
library(spotoroo)
```

```{r}
result <- hotspot_cluster(vic_hotspot_test,
                          lon = "longitude",
                          lat = "latitude",
                          obsTime = "load_dt",
                          activeTime = 24,
                          adjDist = 3000,
                          minPts = 4,
                          minTime = 3,
                          ignitionCenter = "mean",
                          timeUnit = "h",
                          timeStep = 1)
```

```{r}
summary(result)
```


```{r}
plot(result, bg = plot_vic_map())
```

```{r}
plot(result, cluster = c(1,2,3,4))
```

```{r}
test <- read.csv("2020-2021hotpots.csv")
test$datetime <- as.Date(test$datetime)
```





